//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantPOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restoranDBEntities1 : DbContext
    {
        public restoranDBEntities1()
            : base("name=restoranDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<meni> menis { get; set; }
        public virtual DbSet<porez> porezs { get; set; }
        public virtual DbSet<pravneOsobe> pravneOsobes { get; set; }
        public virtual DbSet<proizvod> proizvods { get; set; }
        public virtual DbSet<racun> racuns { get; set; }
        public virtual DbSet<stavkeRacuna> stavkeRacunas { get; set; }
    }
}
